read.table(weight_chart.txt)
read.table(weight_chart)
weight_chart.txt
?read.table()
read.table(weight_chart.txt, header = TRUE)
read.table("weight_chart.txt", header = TRUE)
read.table(weight_chart.txt, header = TRUE)
getwd(weight_chart.txt)
setwd(weight_chart.txt)
read.table(file = weight_chart.txt)
read.table(file = weight_chart.txt)
read.table("bimm143_05_rstats/weight_chart.txt")
read.table("bimm143_05_rstats/weight_chart.txt", header = TRUE)
weight <- read.table("bimm143_05_rstats/weight_chart.txt", header = TRUE)
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age" )
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age", type = b )
?plot
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age" )
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age", type=b)
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age", type=p)
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age", type=l)
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age")
plot(weight, pch = 15, cex = 1.5, lwd = 2, ylim = c(2,10), xlab = "Age (months)", ylab = "Weight (kg)", main = "Baby Weight with Age", type = "b")
read.table("bimm143_05_rstats/feature_counts.txt")
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE)
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "/t")
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "/t")
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "/t")
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "/t")
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "")
read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "1")
mouse <- read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "/t")
mouse <- read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep = "\t")
barplot(mouse$Count)
barplot(mouse$Count, horiz=TRUE, ylab="Count", names.arg=Feature, main="Features in Genome", las=1 )
barplot(mouse$Count, horiz=TRUE, ylab="Count", names.arg$Feature, main="Features in Genome", las=1 )
barplot(mouse$Count, horiz=TRUE, ylab="Count", names.arg = "Feature", main="Features in Genome", las=1 )
barplot(mouse$Count, horiz=TRUE, ylab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1 )
barplot(mouse$Count, horiz=TRUE, xlab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1 )
par()$mar
barplot(mouse$Count, horiz=TRUE, xlab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1, par(5.1, 5, 4.1, 2.1) )
barplot(mouse$Count, horiz=TRUE, xlab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1, par(c(5.1, 5, 4.1, 2.1)) )
barplot(mouse$Count, horiz=TRUE, xlab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1)
?par()
par()$mar = c(5.1, 10, 4.1, 2.1)
par(mar=c(5.1,10,4.1,2.1))
barplot(mouse$Count, horiz=TRUE, xlab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1)
par(mar=c(5.1,12,4.1,2.1))
barplot(mouse$Count, horiz=TRUE, xlab="Count", names.arg = mouse$Feature, main="Features in Genome", las=1)
barplot("bimm143_05_rstats/male_female_counts.txt")
barplot("bimm143_05_rstats/male_female_counts.txt",col=rainbow(10))
?read.table
read.table("bimm143_05_rstats/male_female_counts.txt")
counts <- read.delim("bimm143_05_rstats/male_female_counts.txt")
barplot(counts)
barplot(counts, col=rainbow(10))
View(counts)
barplot(counts, col=rainbow(10))
mf <- read.delim("bimm143_05_rstats/male_female_counts.txt")
View(counts)
View(counts)
barplot(counts$Count)
barplot(counts$Count, names.arg=counts$Sample, las=2, horiz=TRUE)
barplot(counts$Count, names.arg=counts$Sample, las=2, horiz=TRUE, col=rainbow(10))
barplot(counts$Count, names.arg=counts$Sample, las=2, horiz=TRUE, col=c("blue", "red"))
barplot(counts$Count, names.arg=counts$Sample, las=2, horiz=TRUE, col=c("blue2", "red2"))
barplot(counts$Count, names.arg=counts$Sample, las=2,  col=c("blue2", "red2"))
barplot(counts$Count, names.arg=counts$Sample, las=2, col=c("blue2", "red2"))
par(mar=c(6, 6, 6, 6))
par(mar=c(6, 6, 6, 6))
barplot(counts$Count, names.arg=counts$Sample, las=2, col=c("blue2", "red2"))
