---
title: 'Class 6: R Functions'
author: "Arya Jahan"
date: "April 18th, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **Class 6** R Markdown document with my *code* and notes for the day.

```{r}
plot(1:10, typ="l", col="blue")
```

## Reading in files practice

There are 3 files to read.

```{r}
read.table("test1.txt", header = TRUE, sep=",")
```

```{r}
read.table("test2.txt", header=TRUE, sep="$")
```

```{r}
read.table("test3.txt", header = FALSE, sep="")
```


## Functions

Our first function example:

```{r}
add <- function(x,y=1) {
  # The body!
  x+y
}
```

```{r}
add(10)
```
```{r}
add(10,10)
```

```{r}
add( c(1,2,3))
```

```{r}
add( c(1,2,3), 4)
```

Errors to Function:

```{r}
#add(1, "b")
```

```{r}
#add(1, 2, 4)
```

### Another Example

```{r}
rescale <- function(x) {   
  rng <-range(x, na.rm=TRUE)   
  (x - rng[1]) / (rng[2] - rng[1])
  }
```

```{r}
rescale2 <- function(x, na.rm=TRUE) {   
  
  if(!is.numeric(x)) {
    stop("Give Numbers Please")
  }
  
  rng <-range(x, na.rm=na.rm)   
  (x - rng[1]) / (rng[2] - rng[1])
  }
```

Non-Numeric Error Example
```{r}
#rescale2( c(1,10, "string"))
```

NA Error Example
```{r}
rescale2( c(1,3,NA,10), na.rm = FALSE)
```


```{r}
rescale(1:10)
```

```{r}
#How would you get your function to work here?
rescale( c(1,2,NA,3,10))
```

```{r}
x <- c(1,2,NA,3,10)
rng <-range(x, na.rm=TRUE)   
rng
(x - rng[1]) / (rng[2] - rng[1])
```


Give Numbers!
```{r}
#What should your function do here?
#rescale2( c(1,10,"string"))
```


```{r}
x <- c(1,10,"string")

is.numeric(x)

#range(x, na.rm=TRUE)
```


```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {   
  
  rng <-range(x, na.rm=na.rm)   
  print("Hello")  
  
  answer <-(x - rng[1]) / (rng[2] - rng[1])  
  
  print("is it me you are looking for?")   
  
  if(plot) {      
    plot(answer, typ="b", lwd=4)
    print("Please don't sing again...")
  }   
  print("I can see it in ...")
  return(answer)}
```

```{r}
rescale3( c(1,3,NA,10))
```

```{r}
rescale3( c(1,3,NA,10), plot=TRUE)
```
